#!/bin/bash 			  
				# first line specifies shell
#$ -V		 		# inherit the submission environment
#$ -cwd				# Start job in this directory
#$ -N rect4096			# Name
#$ -o $JOB_NAME.$JOB_ID.out	# output->   out.o&ltjobID>
#$ -e $JOB_NAME.$JOB_ID.err	# error -> error.o&ltjobID>
#$ -pe 16way 4096		# 16 tasks/node, 64 cores total
#$ -l h_rt=02:00:00		# 15 mins runtime
#$ -q normal			# Use normal queue.
set -x                          #Echo all commands.
ibrun ./MultTime $WORK/SCALE26-RMAT/rmat26.txt $WORK/SCALE26-RMAT/fringe_scale26_rect8192_sparse1000
