#!/bin/bash
#PBS -A CSC103
#PBS -l nodes=4096
#PBS -l walltime=01:59:00
#PBS -N spGEMMexp_ER_25_65536
#PBS -j oe
cd $MEMBERWORK/csc103

export OMP_NUM_THREADS=1
aprun -n 65536 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 256 256 1 ER 25 16 column
aprun -n 65522 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 181 181 2 ER 25 16 column
aprun -n 65536 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 128 128 4 ER 25 16 column
aprun -n 64800 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 90 90 8 ER 25 16 column
aprun -n 63948 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 73 73 12 ER 25 16 column
aprun -n 65536 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 64 64 16 ER 25 16 column

export OMP_NUM_THREADS=2
aprun -n 32761 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 181 181 1 ER 25 16 column
aprun -n 32768 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 128 128 2 ER 25 16 column
aprun -n 32400 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 90 90 4 ER 25 16 column
aprun -n 32768 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 64 64 8 ER 25 16 column
aprun -n 32448 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 52 52 12 ER 25 16 column
aprun -n 32400 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 45 45 16 ER 25 16 column

export OMP_NUM_THREADS=4
aprun -n 16384 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 128 128 1 ER 25 16 column
aprun -n 16200 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 90 90 2 ER 25 16 column
aprun -n 16384 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 64 64 4 ER 25 16 column
aprun -n 16200 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 45 45 8 ER 25 16 column
aprun -n 15552 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 36 36 12 ER 25 16 column
aprun -n 16384 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 32 32 16 ER 25 16 column

export OMP_NUM_THREADS=8
aprun -n 8100 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 90 90 1 ER 25 16 column
aprun -n 8192 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 64 64 2 ER 25 16 column
aprun -n 8100 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 45 45 4 ER 25 16 column
aprun -n 8192 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 32 32 8 ER 25 16 column
aprun -n 8112 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 26 26 12 ER 25 16 column
aprun -n 7744 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 22 22 16 ER 25 16 column

export OMP_NUM_THREADS=16
aprun -n 4096 -d 16 -N 1 ./mpipspgemm 64 64 1 ER 25 16 column
aprun -n 4050 -d 16 -N 1 ./mpipspgemm 45 45 2 ER 25 16 column
aprun -n 4096 -d 16 -N 1 ./mpipspgemm 32 32 4 ER 25 16 column
aprun -n 3872 -d 16 -N 1 ./mpipspgemm 22 22 8 ER 25 16 column
aprun -n 3888 -d 16 -N 1 ./mpipspgemm 18 18 12 ER 25 16 column
aprun -n 4096 -d 16 -N 1 ./mpipspgemm 16 16 16 ER 25 16 column
