#!/bin/bash
#PBS -q debug
#PBS -l mppwidth=10000
#PBS -l walltime=00:30:00
#PBS -j eo
#PBS -V

export IPM_LOGDIR="."
export IPM_LOG="full"
cd $SCRATCH
aprun -n 10000 ./graph500_withipm Force 32 FastGen
