#!/bin/bash
#PBS -q debug
#PBS -l mppwidth=10000
#PBS -l walltime=00:30:00
#PBS -j eo
#PBS -V

cd $SCRATCH
export MPICH_RANK_REORDER_DISPLAY=1
export MPICH_RANK_REORDER_METHOD=3
aprun -n 10000 ./graph500_withipm Force 32 FastGen
