#!/bin/bash 			  
				# first line specifies shell
#$ -V		 		# inherit the submission environment
#$ -cwd				# Start job in this directory
#$ -N galerkin64			# Name
#$ -o $JOB_NAME.$JOB_ID.out	# output->   out.o&ltjobID>
#$ -e $JOB_NAME.$JOB_ID.err	# error -> error.o&ltjobID>
#$ -pe 16way 64		# 16 tasks/node, 64 cores total
#$ -l h_rt=00:15:00		# 15 mins runtime
#$ -q normal			# Use normal queue.
set -x                          #Echo all commands.
ibrun ./MultTime $WORK/SCALE23-RMAT/input1_0 $WORK/SCALE23-RMAT/galerkin_scale23_order8
