#!/bin/bash 			  
				# first line specifies shell
#$ -V		 		# inherit the submission environment
#$ -cwd				# Start job in this directory
#$ -N btwcent49			# Name
#$ -o $JOB_NAME.$JOB_ID.out	# output->   out.o&ltjobID>
#$ -e $JOB_NAME.$JOB_ID.err	# error -> error.o&ltjobID>
#$ -pe 16way 64 		# 16 tasks/node, 16 cores total
export MY_NSLOTS=49
#$ -l h_rt=00:20:00		# 15 mins runtime
#$ -q normal			# Use normal queue.
set -x                          #Echo all commands.
ibrun ./MultTime $WORK/SCALE22-RMAT/input1_0 $WORK/SCALE22-RMAT/input2_0
