#!/bin/bash -l

#SBATCH -p debug
#SBATCH -N 16
#SBATCH -t 00:30:00
#SBATCH -J mouse_gene
#SBATCH -o mouse_gene_rand20.o%j

MAT=/project/projectdirs/m1982/ariful/symmetric/mouse_gene.mtx

export OMP_NUM_THREADS=24
N=16
n=16

srun -N $N -n $n -c 24  --ntasks-per-node=1 --cpu_bind=cores ../../mcl -M $MAT -I 2 -p .0001 -S 1100 -R 1400  -pct .9 -base 1 -rand 1 -phases 20

