#!/bin/bash
#PBS -A CSC103
#PBS -l nodes=128
#PBS -l walltime=02:59:00
#PBS -N spGEMMexp_G500_26_2048
#PBS -j oe
cd $MEMBERWORK/csc103

export OMP_NUM_THREADS=1
aprun -n 2025 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 45 45 1 G500 26 16 column
aprun -n 2048 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 32 32 2 G500 26 16 column
aprun -n 1936 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 22 22 4 G500 26 16 column
aprun -n 2048 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 16 16 8 G500 26 16 column
aprun -n 2028 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 13 13 12 G500 26 16 column
aprun -n 1936 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 11 11 16 G500 26 16 column

export OMP_NUM_THREADS=2
aprun -n 1024 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 32 32 1 G500 26 16 column
aprun -n 968 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 22 22 2 G500 26 16 column
aprun -n 1024 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 16 16 4 G500 26 16 column
aprun -n 968 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 11 11 8 G500 26 16 column
aprun -n 972 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 9 9 12 G500 26 16 column
aprun -n 1024 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 8 8 16 G500 26 16 column

export OMP_NUM_THREADS=4
aprun -n 484 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 22 22 1 G500 26 16 column
aprun -n 512 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 16 16 2 G500 26 16 column
aprun -n 484 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 11 11 4 G500 26 16 column
aprun -n 512 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 8 8 8 G500 26 16 column
aprun -n 432 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 6 6 12 G500 26 16 column
aprun -n 400 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 5 5 16 G500 26 16 column

export OMP_NUM_THREADS=8
aprun -n 256 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 16 16 1 G500 26 16 column
aprun -n 242 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 11 11 2 G500 26 16 column
aprun -n 256 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 8 8 4 G500 26 16 column
aprun -n 200 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 5 5 8 G500 26 16 column
aprun -n 192 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 4 4 12 G500 26 16 column
aprun -n 256 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 4 4 16 G500 26 16 column

export OMP_NUM_THREADS=16
aprun -n 121 -d 16 -N 1 ./mpipspgemm 11 11 1 G500 26 16 column
aprun -n 128 -d 16 -N 1 ./mpipspgemm 8 8 2 G500 26 16 column
aprun -n 100 -d 16 -N 1 ./mpipspgemm 5 5 4 G500 26 16 column
aprun -n 128 -d 16 -N 1 ./mpipspgemm 4 4 8 G500 26 16 column
aprun -n 108 -d 16 -N 1 ./mpipspgemm 3 3 12 G500 26 16 column
aprun -n 64 -d 16 -N 1 ./mpipspgemm 2 2 16 G500 26 16 column
