#!/bin/bash
#PBS -A CSC103
#PBS -l nodes=2048
#PBS -l walltime=00:59:00
#PBS -N spGEMMexp_G500_24_32768
#PBS -j oe
cd $MEMBERWORK/csc103

export OMP_NUM_THREADS=1
aprun -n 32761 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 181 181 1 G500 24 16 column
aprun -n 32768 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 128 128 2 G500 24 16 column
aprun -n 32400 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 90 90 4 G500 24 16 column
aprun -n 32768 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 64 64 8 G500 24 16 column
aprun -n 32448 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 52 52 12 G500 24 16 column
aprun -n 32400 -d 1 -N 16 -S 8 -cc depth ./mpipspgemm 45 45 16 G500 24 16 column

export OMP_NUM_THREADS=2
aprun -n 16384 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 128 128 1 G500 24 16 column
aprun -n 16200 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 90 90 2 G500 24 16 column
aprun -n 16384 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 64 64 4 G500 24 16 column
aprun -n 16200 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 45 45 8 G500 24 16 column
aprun -n 15552 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 36 36 12 G500 24 16 column
aprun -n 16384 -d 2 -N 8 -S 4 -cc depth ./mpipspgemm 32 32 16 G500 24 16 column

export OMP_NUM_THREADS=4
aprun -n 8100 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 90 90 1 G500 24 16 column
aprun -n 8192 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 64 64 2 G500 24 16 column
aprun -n 8100 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 45 45 4 G500 24 16 column
aprun -n 8192 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 32 32 8 G500 24 16 column
aprun -n 8112 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 26 26 12 G500 24 16 column
aprun -n 7744 -d 4 -N 4 -S 2 -cc depth ./mpipspgemm 22 22 16 G500 24 16 column

export OMP_NUM_THREADS=8
aprun -n 4096 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 64 64 1 G500 24 16 column
aprun -n 4050 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 45 45 2 G500 24 16 column
aprun -n 4096 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 32 32 4 G500 24 16 column
aprun -n 3872 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 22 22 8 G500 24 16 column
aprun -n 3888 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 18 18 12 G500 24 16 column
aprun -n 4096 -d 8 -N 2 -S 1 -cc numa_node ./mpipspgemm 16 16 16 G500 24 16 column

export OMP_NUM_THREADS=16
aprun -n 2025 -d 16 -N 1 ./mpipspgemm 45 45 1 G500 24 16 column
aprun -n 2048 -d 16 -N 1 ./mpipspgemm 32 32 2 G500 24 16 column
aprun -n 1936 -d 16 -N 1 ./mpipspgemm 22 22 4 G500 24 16 column
aprun -n 2048 -d 16 -N 1 ./mpipspgemm 16 16 8 G500 24 16 column
aprun -n 2028 -d 16 -N 1 ./mpipspgemm 13 13 12 G500 24 16 column
aprun -n 1936 -d 16 -N 1 ./mpipspgemm 11 11 16 G500 24 16 column
